version: '3.4'

services:
 catalogdb:
   image: postgres
 basketdb:
   image: postgres
   build:
    dockerfile: Services/Catalog/CatalogApi/Dockerfile

volumes:
   postgres_catalog:
   postgres_basket: 